"""
PDF Report Generator using Jinja2 templates + WeasyPrint.

Generates A4 portrait PDF reports with:
1. Summary KPIs
2. Department composition
3. Gross profit factor analysis
4. OOS / Discount highlights
"""

from __future__ import annotations

import io
from datetime import datetime
from typing import Any

from jinja2 import Template
from loguru import logger

from app.components import get_sales_column
from app.data import load_sales_monthly

# HTML template for the PDF report
PDF_TEMPLATE = """
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<style>
    @page {
        size: A4 portrait;
        margin: 15mm;
    }
    body {
        font-family: 'Noto Sans JP', 'Helvetica Neue', Arial, sans-serif;
        font-size: 10pt;
        color: #333;
        line-height: 1.5;
    }
    h1 {
        font-size: 16pt;
        color: #1a5276;
        border-bottom: 2px solid #1a5276;
        padding-bottom: 5px;
    }
    h2 {
        font-size: 13pt;
        color: #2c3e50;
        margin-top: 15px;
        border-left: 4px solid #3498db;
        padding-left: 8px;
    }
    .header {
        text-align: center;
        margin-bottom: 20px;
    }
    .header h1 {
        margin-bottom: 5px;
        border-bottom: none;
    }
    .header .subtitle {
        color: #666;
        font-size: 11pt;
    }
    .kpi-grid {
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        gap: 10px;
        margin: 15px 0;
    }
    .kpi-card {
        border: 1px solid #ddd;
        border-radius: 6px;
        padding: 10px;
        text-align: center;
        background: #f9f9f9;
    }
    .kpi-label {
        font-size: 8pt;
        color: #666;
        margin-bottom: 3px;
    }
    .kpi-value {
        font-size: 14pt;
        font-weight: bold;
        color: #1a5276;
    }
    .kpi-delta {
        font-size: 8pt;
        margin-top: 2px;
    }
    .delta-positive { color: #27ae60; }
    .delta-negative { color: #e74c3c; }
    table {
        width: 100%;
        border-collapse: collapse;
        margin: 10px 0;
        font-size: 9pt;
    }
    th, td {
        border: 1px solid #ddd;
        padding: 6px 8px;
        text-align: right;
    }
    th {
        background: #2c3e50;
        color: white;
        font-weight: bold;
    }
    td:first-child, th:first-child {
        text-align: left;
    }
    tr:nth-child(even) { background: #f5f5f5; }
    .footer {
        margin-top: 30px;
        text-align: center;
        font-size: 8pt;
        color: #999;
        border-top: 1px solid #ddd;
        padding-top: 5px;
    }
    .section { page-break-inside: avoid; }
</style>
</head>
<body>

<div class="header">
    <h1>Chief Dashboard - 月次レポート</h1>
    <div class="subtitle">期間: {{ ym }} | 生成日時: {{ generated_at }}</div>
</div>

<div class="section">
<h2>1. サマリKPI</h2>
<div class="kpi-grid">
    <div class="kpi-card">
        <div class="kpi-label">売上 (税抜)</div>
        <div class="kpi-value">฿{{ "{:,.0f}".format(total_sales) }}</div>
        {% if sales_yoy %}
        <div class="kpi-delta {{ 'delta-positive' if sales_yoy > 0 else 'delta-negative' }}">
            前年差: {{ "{:+,.0f}".format(sales_yoy) }}
        </div>
        {% endif %}
    </div>
    <div class="kpi-card">
        <div class="kpi-label">粗利額</div>
        <div class="kpi-value">฿{{ "{:,.0f}".format(total_profit) }}</div>
    </div>
    <div class="kpi-card">
        <div class="kpi-label">粗利率</div>
        <div class="kpi-value">{{ "{:.1f}".format(margin_pct) }}%</div>
    </div>
    <div class="kpi-card">
        <div class="kpi-label">値引率</div>
        <div class="kpi-value">{{ "{:.1f}".format(discount_rate) }}%</div>
    </div>
</div>
</div>

<div class="section">
<h2>2. 部門別構成比</h2>
<table>
    <tr>
        <th>部門</th>
        <th>売上</th>
        <th>売上構成比</th>
        <th>粗利額</th>
        <th>粗利構成比</th>
        <th>粗利率</th>
    </tr>
    {% for dept in departments %}
    <tr>
        <td>{{ dept.name }}</td>
        <td>{{ "{:,.0f}".format(dept.sales) }}</td>
        <td>{{ "{:.1f}".format(dept.sales_pct) }}%</td>
        <td>{{ "{:,.0f}".format(dept.profit) }}</td>
        <td>{{ "{:.1f}".format(dept.profit_pct) }}%</td>
        <td>{{ "{:.1f}".format(dept.margin) }}%</td>
    </tr>
    {% endfor %}
</table>
</div>

<div class="section">
<h2>3. 要注意項目</h2>
{% if alerts %}
<ul>
    {% for alert in alerts %}
    <li>{{ alert }}</li>
    {% endfor %}
</ul>
{% else %}
<p>特に要注意項目はありません。</p>
{% endif %}
</div>

<div class="footer">
    Chief Dashboard | Generated by {{ generated_by }} | {{ generated_at }}
</div>

</body>
</html>
"""


def generate_report_pdf(
    filters: dict[str, Any],
    generated_by: str = "system",
) -> bytes | None:
    """
    Generate a PDF report based on current filters.

    Returns PDF bytes or None if generation fails.
    """
    try:
        from weasyprint import HTML
    except ImportError:
        logger.warning("WeasyPrint not installed, generating HTML-only fallback")
        # Fall through to generate HTML, return it as bytes
        return _generate_html_report(filters, generated_by).encode("utf-8")

    html_content = _generate_html_report(filters, generated_by)

    try:
        pdf_bytes = HTML(string=html_content).write_pdf()
        return pdf_bytes
    except Exception as e:
        logger.error(f"PDF generation failed: {e}")
        # Return HTML as fallback
        return html_content.encode("utf-8")


def _generate_html_report(
    filters: dict[str, Any],
    generated_by: str = "system",
) -> str:
    """Generate HTML report content."""
    sales_col = get_sales_column(filters)

    # Load data
    df = load_sales_monthly()

    # Apply filters
    df_f = df.copy()
    if filters.get("ym"):
        df_f = df_f[df_f["ym"] == filters["ym"]]
    if filters.get("store_ids"):
        df_f = df_f[df_f["store_id"].isin(filters["store_ids"])]
    if filters.get("dept_ids"):
        df_f = df_f[df_f["dept_id"].isin(filters["dept_ids"])]

    # Calculate KPIs
    total_sales = df_f[sales_col].sum() if not df_f.empty else 0
    total_gross = df_f["gross_sales_ex_tax"].sum() if not df_f.empty else 0
    total_profit = df_f["gross_profit"].sum() if not df_f.empty else 0
    total_net = df_f["net_sales_ex_tax"].sum() if not df_f.empty else 0
    margin_pct = (total_profit / total_net * 100) if total_net else 0
    discount = df_f["discount_amount_ex_tax"].sum() if not df_f.empty else 0
    discount_rate = (discount / total_gross * 100) if total_gross else 0

    sales_yoy = df_f[f"{'net_sales' if 'net' in sales_col else 'gross_sales'}_yoy"].sum() if not df_f.empty else 0

    # Department breakdown
    departments = []
    if not df_f.empty:
        dept_agg = df_f.groupby("dept_name").agg({
            sales_col: "sum",
            "gross_profit": "sum",
            "net_sales_ex_tax": "sum",
        }).reset_index()

        total_dept_sales = dept_agg[sales_col].sum()
        total_dept_profit = dept_agg["gross_profit"].sum()

        for _, row in dept_agg.iterrows():
            departments.append({
                "name": row["dept_name"],
                "sales": row[sales_col],
                "sales_pct": (row[sales_col] / total_dept_sales * 100) if total_dept_sales else 0,
                "profit": row["gross_profit"],
                "profit_pct": (row["gross_profit"] / total_dept_profit * 100) if total_dept_profit else 0,
                "margin": (row["gross_profit"] / row["net_sales_ex_tax"] * 100) if row["net_sales_ex_tax"] else 0,
            })

    # Alerts
    alerts = []
    if not df_f.empty:
        # Check for margin deterioration
        if "gross_margin_yoy_diff" in df_f.columns:
            bad_margin = df_f[df_f["gross_margin_yoy_diff"] < -2]
            if not bad_margin.empty:
                for _, row in bad_margin.iterrows():
                    alerts.append(
                        f"粗利率悪化: {row.get('store_name', '')} × {row.get('dept_name', '')} "
                        f"(前年差 {row['gross_margin_yoy_diff']:+.1f}pt)"
                    )

        # High discount rate
        high_discount = df_f[df_f["discount_rate_pct"] > 5]
        if not high_discount.empty:
            for _, row in high_discount.iterrows():
                alerts.append(
                    f"高値引率: {row.get('store_name', '')} × {row.get('dept_name', '')} "
                    f"({row['discount_rate_pct']:.1f}%)"
                )

    alerts = alerts[:10]  # Limit alerts

    # Render template
    template = Template(PDF_TEMPLATE)
    html = template.render(
        ym=filters.get("ym", "N/A"),
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M"),
        generated_by=generated_by,
        total_sales=total_sales,
        sales_yoy=sales_yoy,
        total_profit=total_profit,
        margin_pct=margin_pct,
        discount_rate=discount_rate,
        departments=departments,
        alerts=alerts,
    )

    return html
